vzstats: print error in case of unknown option
Signed-off-by: Kir Kolyshkin <kir@openvz.org>

diff --git a/vzstats b/vzstats
--- a/vzstats
+++ b/vzstats
@@ -69,6 +69,7 @@ while [ $# -gt 0 ]; do
 		usage 0
 		;;
 	*)
+		echo "ERROR: Unknown option $1" 1>&2
 		usage 1
 		;;
 	esac
